services:
  mongodb:
    image: mongo:latest
    container_name: db_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: supersenha
      SRV_ASAAS_API_KEY: ${SRV_ASAAS_API_KEY}
    volumes: 
      - ./tmp_data/mongodb_data:/data/db
    ports:
      - 27017:27017
    networks:
      - user-bridge

networks:
  user-bridge:
    external: true
