version: '3.9'

services:
  
  mongodb:
    image: mongo:latest
    container_name: db_mongo
    # restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: supersenha
    volumes: 
     - ./tmp_data/mongodb_data:/data/db
    ports:
      - 27017:27017
    networks:
      - user-bridge
 

networks:
  user-bridge:
    name: user-bridge