version: '3.9'

services:
  
  
  dbpostgres:
    image: postgres:15-alpine
    container_name: dbpostgres
    # restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersenha
      POSTGRES_DB: oticahope_dev
    volumes: 
     
      - ./tmp_data/postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - user-bridge

  redis:
    container_name: redis
    image: redis:7.0.7
    # restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./tmp_data/redis_data:/data
    networks:
      - user-bridge
  
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12-management-alpine
    # restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=supersenha
    networks:
      - user-bridge
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./tmp_data/rabbitmq_data:/var/lib/rabbitmq

networks:
  user-bridge:
    name: user-bridge
