services:
  mongodb:
    image: mongo:latest
    container_name: db_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: supersenha
      SRV_ASAAS_API_KEY: ${SRV_ASAAS_API_KEY}
    volumes: 
      - ./tmp_data/mongodb_data:/data/db
    ports:
      - 27017:27017
    networks:
      - user-bridge

  localstack:
    image: localstack/localstack
    container_name: localstack
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    networks:
      - user-bridge
    ports:
      - "4566:4566"  # Porta principal para interações com LocalStack
    volumes:
      - ./tmp_data/localstack_data:/tmp/localstack

networks:
  user-bridge:
    external: true